const ServicesArray = [
    {
        Id: 1,
        CreationTime: null,
        LastModificationTime: null,
        LastModifierUserId: null,
        IsDeleted: null,
        DeleterUserId: null,
        DeletionTime: null,
        ItemType: "Remainder",
        Name: "Coaches",
        Description: "Coaches",
        DefaultUnits: 1,
        DefaultQuantity: 1,
        DefaultPrice: "$0.00"
    },
    {
        Id: 2,
        CreationTime: null,
        LastModificationTime: null,
        LastModifierUserId: null,
        IsDeleted: null,
        DeleterUserId: null,
        DeletionTime: null,
        ItemType: "Coaches",
        Name: "Coaches",
        Description: "Coaches",
        DefaultUnits: 1,
        DefaultQuantity: 1,
        DefaultPrice: "$0.00"
    },
    {
        Id: 3,
        CreationTime: null,
        LastModificationTime: null,
        LastModifierUserId: null,
        IsDeleted: null,
        DeleterUserId: null,
        DeletionTime: null,
        ItemType: "Trailers",
        Name: "Trailers",
        Description: "Trailers",
        DefaultUnits: 1,
        DefaultQuantity: 1,
        DefaultPrice: "$0.00"
    },
    {
        Id: 4,
        CreationTime: null,
        LastModificationTime: null,
        LastModifierUserId: null,
        IsDeleted: null,
        DeleterUserId: null,
        DeletionTime: null,
        ItemType: "Drivers",
        Name: "Drivers",
        Description: "Drivers",
        DefaultUnits: 1,
        DefaultQuantity: 1,
        DefaultPrice: "$0.00"
    },
    {
        Id: 5,
        CreationTime: null,
        LastModificationTime: null,
        LastModifierUserId: null,
        IsDeleted: null,
        DeleterUserId: null,
        DeletionTime: null,
        ItemType: "StarDrivers",
        Name: "Star Drivers",
        Description: "Star Drivers",
        DefaultUnits: 1,
        DefaultQuantity: 1,
        DefaultPrice: "$0.00"
    },
    {
        Id: 6,
        CreationTime: null,
        LastModificationTime: null,
        LastModifierUserId: null,
        IsDeleted: null,
        DeleterUserId: null,
        DeletionTime: null,
        ItemType: "TrailerDrivers",
        Name: "Trailer Drivers",
        Description: "Trailer Drivers",
        DefaultUnits: 1,
        DefaultQuantity: 1,
        DefaultPrice: "$0.00"
    },
    {
        Id: 7,
        CreationTime: null,
        LastModificationTime: null,
        LastModifierUserId: null,
        IsDeleted: null,
        DeleterUserId: null,
        DeletionTime: null,
        ItemType: "Cleaning",
        Name: "Cleaning",
        Description: "Cleaning",
        DefaultUnits: 1,
        DefaultQuantity: 1,
        DefaultPrice: "$0.00"
    },
    {
        Id: 8,
        CreationTime: null,
        LastModificationTime: null,
        LastModifierUserId: null,
        IsDeleted: null,
        DeleterUserId: null,
        DeletionTime: null,
        ItemType: "Fuel",
        Name: "Fuel",
        Description: "Fuel",
        DefaultUnits: 1,
        DefaultQuantity: 1,
        DefaultPrice: "$0.00"
    },
    {
        Id: 9,
        CreationTime: null,
        LastModificationTime: null,
        LastModifierUserId: null,
        IsDeleted: null,
        DeleterUserId: null,
        DeletionTime: null,
        ItemType: "DOT",
        Name: "DOT Charges",
        Description: "DOT Charges",
        DefaultUnits: 1,
        DefaultQuantity: 1,
        DefaultPrice: "$300.00"
    },
    {
        Id: 10,
        CreationTime: null,
        LastModificationTime: null,
        LastModifierUserId: null,
        IsDeleted: null,
        DeleterUserId: null,
        DeletionTime: null,
        ItemType: "Internet",
        Name: "Internet",
        Description: "Internet",
        DefaultUnits: 1,
        DefaultQuantity: 1,
        DefaultPrice: "$125.00"
    },
    {
        Id: 11,
        CreationTime: null,
        LastModificationTime: null,
        LastModifierUserId: null,
        IsDeleted: null,
        DeleterUserId: null,
        DeletionTime: null,
        ItemType: "Satellite",
        Name: "Satellite",
        Description: "Satellite",
        DefaultUnits: 1,
        DefaultQuantity: 1,
        DefaultPrice: "$0.00"
    },
    {
        Id: 12,
        CreationTime: null,
        LastModificationTime: null,
        LastModifierUserId: null,
        IsDeleted: null,
        DeleterUserId: null,
        DeletionTime: null,
        ItemType: "EngSrv",
        Name: "Engine Service",
        Description: "Engine Service",
        DefaultUnits: 1,
        DefaultQuantity: 1,
        DefaultPrice: "$0.00"
    },
    {
        Id: 13,
        CreationTime: null,
        LastModificationTime: null,
        LastModifierUserId: null,
        IsDeleted: null,
        DeleterUserId: null,
        DeletionTime: null,
        ItemType: "DrvSrv",
        Name: "Driver Services",
        Description: "Driver Services",
        DefaultUnits: 1,
        DefaultQuantity: 1,
        DefaultPrice: "$0.00"
    },
    {
        Id: 14,
        CreationTime: null,
        LastModificationTime: null,
        LastModifierUserId: null,
        IsDeleted: null,
        DeleterUserId: null,
        DeletionTime: null,
        ItemType: "Hotel",
        Name: "Hotel Buyout",
        Description: "Hotel Buyout",
        DefaultUnits: 1,
        DefaultQuantity: 1,
        DefaultPrice: "$0.00"
    },
    {
        Id: 15,
        CreationTime: null,
        LastModificationTime: null,
        LastModifierUserId: null,
        IsDeleted: null,
        DeleterUserId: null,
        DeletionTime: null,
        ItemType: "FuelAdmin",
        Name: "Fuel Admin Fee",
        Description: "Fuel Admin Fee",
        DefaultUnits: 1,
        DefaultQuantity: 1,
        DefaultPrice: "$0.00"
    },
    {
        Id: 16,
        CreationTime: null,
        LastModificationTime: null,
        LastModifierUserId: null,
        IsDeleted: null,
        DeleterUserId: null,
        DeletionTime: null,
        ItemType: "Toll",
        Name: "Toll",
        Description: "Toll",
        DefaultUnits: 1,
        DefaultQuantity: 1,
        DefaultPrice: "$0.00"
    },
    {
        Id: 17,
        CreationTime: null,
        LastModificationTime: null,
        LastModifierUserId: null,
        IsDeleted: null,
        DeleterUserId: null,
        DeletionTime: null,
        ItemType: "Payroll",
        Name: "Payroll Fee",
        Description: "Payroll Fee",
        DefaultUnits: 1,
        DefaultQuantity: 1,
        DefaultPrice: "$0.00"
    }
]

export default ServicesArray;